# ===================================================================
# Spring Boot Application Properties for 'elk' Project
# ===================================================================

# Name of the Spring Boot application
spring.application.name=elk

# Port number on which the application will run
server.port=8082

# Path to the Logback configuration file for logging settings
logging.config=classpath:logback-spring.xml
